google_project_id       = "kubernetes-ferat"
google_bucket_name      = "fuchicorp-ferat"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"